server:
  port: 8081

spring:
  application:
    name: hello-resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000

oauth2:
  cookie-name:
    access-cookie-name: access_token

